### ISSUE TITLE
boundary or interface tracking in IB method

### ISSUE THREAD

**Issue by Haider-BA** [obrienadam/Phase#1]
Hi,
Can you provide the reference how you are tracking the boundary/interface in immersed boundary method? I have a similar problem, to find the intersection points of an immersed boundary with the underlying structured grid (i.e. X and Y of a curved boundary with horizontal and vertical axis intersection).

Regards

**Comment by obrienadam** [comment]
@Haider-BA ,

The IB method is just the ghost-cell method published by Majumdar et-al, i.e. it's just a matter of finding the nearest point on the IB surface to the internal cells within the IB. Whether it's curved or not does not really matter.
